checking the system for dynamics and energy presence
ubermag/mumax3c pull request #79
Opened 2024-01-23 20:51 UTC by kzqureshi

Check for the system's energy and system's dynamic is added.

2024-01-23 20:52 UTC, kzqureshi commented
- [ ] Test for py checks

2024-01-30 15:03 UTC, kzqureshi commented
Changes from ubermag/micromagnetictests#47 required for proper test for the relaxdriver.

2024-03-01 11:43 UTC, samjrholt requested changes

2024-03-01 11:43 UTC, samjrholt commented on mumax3c/drivers/mindriver.py
> +            raise AttributeError("System's energy is not defined")
```suggestion
            raise RuntimeError("System's energy is not defined")
```

2024-03-01 11:43 UTC, samjrholt commented on mumax3c/drivers/relaxdriver.py
> +            raise AttributeError("System's dynamics is not defined")
```suggestion
            raise RuntimeError("System's dynamics is not defined")
```

2024-03-01 11:43 UTC, samjrholt commented on mumax3c/drivers/relaxdriver.py
> +            raise AttributeError("System's energy is not defined")
```suggestion
            raise RuntimeError("System's energy is not defined")
```

2024-03-01 11:43 UTC, samjrholt commented on mumax3c/drivers/timedriver.py
> +            raise AttributeError("System's dynamics is not defined")
```suggestion
            raise RuntimeError("System's dynamics is not defined")
```

2024-03-01 11:43 UTC, samjrholt commented on mumax3c/drivers/timedriver.py
> +            raise AttributeError("System's energy is not defined")
```suggestion
            raise RuntimeError("System's energy is not defined")
```

2024-03-01 13:53 UTC, lang-m commented on mumax3c/drivers/relaxdriver.py
> +            raise RuntimeError("System's dynamics is not defined")
Relax does not need a dynamics equation

```suggestion
```

2024-03-04 14:57 UTC, samjrholt approved these changes

2024-03-04 14:57 UTC, merged